// Automatically generated by flapigen
package at.jku.ins.chat.ffi;
import androidx.annotation.NonNull;

public final class ChatMessage {

    public ChatMessage(@NonNull String signature, @NonNull String data_type, @NonNull String data) {
        mNativeObj = init(signature, data_type, data);
    }
    private static native long init(@NonNull String signature, @NonNull String data_type, @NonNull String data);

    public final @NonNull String get_signature() {
        String ret = do_get_signature(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_get_signature(long self);

    public final @NonNull String get_data_type() {
        String ret = do_get_data_type(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_get_data_type(long self);

    public final @NonNull String get_data() {
        String ret = do_get_data(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_get_data(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
        }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
            super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ ChatMessage(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}