// Automatically generated by flapigen
package at.jku.ins.chat.ffi;
import androidx.annotation.NonNull;

public final class MessagingClient {

    public MessagingClient(@NonNull String cache) {
        mNativeObj = init(cache);
    }
    private static native long init(@NonNull String cache);

    public final @NonNull String onion_service_from_esk(@NonNull short [] expanded_secret_key) {
        String ret = do_onion_service_from_esk(mNativeObj, expanded_secret_key);

        return ret;
    }
    private static native @NonNull String do_onion_service_from_esk(long self, short [] expanded_secret_key);

    public final @NonNull String onion_service_from_sk(@NonNull short [] secret_key) {
        String ret = do_onion_service_from_sk(mNativeObj, secret_key);

        return ret;
    }
    private static native @NonNull String do_onion_service_from_sk(long self, short [] secret_key);

    public static native @NonNull String get_onion_address(@NonNull short [] public_key);

    public static native short [] generate_key();

    public final @NonNull String send_message(@NonNull String message, @NonNull String onion_address) {
        String ret = do_send_message(mNativeObj, message, onion_address);

        return ret;
    }
    private static native @NonNull String do_send_message(long self, @NonNull String message, @NonNull String onion_address);

    public final void subscribe(@NonNull MessageObserver a0) {
        do_subscribe(mNativeObj, a0);
    }
    private static native void do_subscribe(long self, MessageObserver a0);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MessagingClient(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}